name: Simple Workflow

on:
    push:
        branches:
            - master

jobs:
    hello_world:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Install dependencies
              run: |
                sudo apt-get install pandoc
                pip3 install nbconvert ipykernel
                pip3 install -r requirements.txt
            - name: Run Jupyter Notebook
              run: python3 -m nbconvert --to pdf --execute lab01/pint_and_boiling_point.ipynb
            - run: echo "Done!"
