name: Simple Workflow

on:
    push:
        branches:
            - master

jobs:
    hello_world:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Install dependencies
              run: pip install nbconvert
            - name: Run Jupyter Notebook
              run: python -m nbconvert --to pdf --execute lab01/pint_and_boiling_point.ipynb
            - run: echo "Done!"
